### ISSUE TITLE
Vertical distribution entity crash

### ISSUE THREAD

**Issue by awahlig** [lkempf/casambi-bt-hass#101]
**Describe the bug**
Number entity for vertical distribution is not added due to an exception.

**To Reproduce**
1. Have a Casambi light with vertical control.
2. Install casambi-bt integration.
3. Check to see if a number entity has been added (for me it's not).
4. Check the logs to see the exception (see below).

**Expected behavior**
A number entity is added to control the vertical distribution, no error in the logs.

**Versions**
- HA version: HAOS 2025.1.2
- Integration version: 0.2.0

**Logs**
```
2025-01-11 00:32:22.414 ERROR (MainThread) [homeassistant.components.number] Error adding entity None for domain number with platform casambi_bt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 254, in capability_attributes
    ATTR_STEP: self._calculate_step(min_value, max_value),
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 334, in _calculate_step
    if (native_step := self.native_step) is not None:
                       ^^^^^^^^^^^^^^^^
  File "src/propcache/_helpers_c.pyx", line 80, in propcache._helpers_c.cached_property.__get__
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 321, in native_step
    and self.entity_description.native_step is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypedEntityDescription' object has no attribute 'native_step'
```

**Notes**

Looking at the code, the `TypedEntityDescription` is based on `EntityDescription` from `homeassistant.helpers.entity` which indeed doesn't have `native_step`.

It seems that the number entity expects a number-specific version, i.e. a `NumberEntityDescription` from `homeassistant.components.number`.

**Comment by stbuerger** [comment]
Just after updating to 0.2.0 I'm to also getting

> Error adding entity None for domain number with platform casambi_bt

Additionally my entities got renamed with  **"\_none"** added at the end
   e.g. from _light.mito_raggio_ to _light.mito_raggio\_**none**_

And .. in fact Occhia Mito raggio is a luminair with vertical distribution

Other than this error log entries the integration seems to work as before. But I was not able to find any additional settings/attributes for the vertical distribution.

**Comment by awahlig** [comment]
I fixed both issues and created PRs for them.

crash https://github.com/lkempf/casambi-bt-hass/pull/108
none https://github.com/lkempf/casambi-bt-hass/pull/107

**Comment by awahlig** [comment]
Both PRs have been merged.
