### PR TITLE
Remove unused import of IDENTIFIER_NETWORK_ID

### LINKED ISSUE #54: Unable to import component: cannot import name 'IDENTIFIER_NETWORK_ID'
**Describe the bug**
Can not setup latest version after updating and restarting.
Seems like this bug was introduced in https://github.com/lkempf/casambi-bt-hass/pull/43.

**To Reproduce**
1. Install the latest version
2. Reboot Home Assistant
3. See error

**Expected behavior**
Casambi keeps working as always and has no issues with the `IDENTIFIER_NETWORK_ID` on this line: https://github.com/lkempf/casambi-bt-hass/blob/42bc6c639cb89edbffb0580b6699864ba5a41c72/custom_components/casambi_bt/__init__.py#L22 @CFenner 

**Versions**
- HA version: 2023.12.0b2
- Integration version: 42bc6c639cb89edbffb0580b6699864ba5a41c72

**Logs**
```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 21:00:31 (1 occurrences)
Last logged: 21:00:31

Setup failed for custom integration 'casambi_bt': Unable to import component: cannot import name 'IDENTIFIER_NETWORK_ID' from 'custom_components.casambi_bt.const' (/config/custom_components/casambi_bt/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/casambi_bt/__init__.py", line 22, in <module>
    from .const import DOMAIN, IDENTIFIER_NETWORK_ID
ImportError: cannot import name 'IDENTIFIER_NETWORK_ID' from 'custom_components.casambi_bt.const' (/config/custom_components/casambi_bt/const.py)
```

### PR DESCRIPTION
**Pull request by CFenner**
This fixes #54 

Leftover from https://github.com/lkempf/casambi-bt-hass/pull/43

### CODE REVIEW

**Comment by lkempf** [comment]
Thanks for fixing that. I should try to also get mypy into the CI for this project.

**Comment by CFenner** [comment]
@lkempf the other day I prepared a [PR to run pylint](https://github.com/lkempf/casambi-bt-hass/pull/16/files), maybe that's something to start with.
